import { argv, exit } from 'node:process';

async function authHeaders(token) {
  const h = { accept: 'application/vnd.github+json', 'user-agent': 'slopsieve-cli/0.1' };
  if (token) h.authorization = `Bearer ${token}`;
  return h;
}

async function gh(url, token) {
  const resp = await fetch(url, { headers: await authHeaders(token) });
  const text = await resp.text();
  if (!resp.ok) throw new Error(`GitHub ${resp.status}: ${text.slice(0, 200)}`);
  return JSON.parse(text);
}

function pathLooksLikeTest(p = '') {
  const s = p.toLowerCase();
  return (
    s.includes('/test/') ||
    s.includes('/tests/') ||
    s.includes('__tests__') ||
    s.endsWith('.spec.js') ||
    s.endsWith('.test.js') ||
    s.endsWith('.spec.ts') ||
    s.endsWith('.test.ts') ||
    s.includes('pytest') ||
    s.includes('spec/')
  );
}
function pathLooksLikeDocs(p = '') {
  const s = p.toLowerCase();
  return s.startsWith('docs/') || s.includes('/docs/') || s.endsWith('.md') || s.endsWith('.mdx') || s.includes('readme');
}
function pathLooksLikeCode(p = '') {
  const s = p.toLowerCase();
  const exts = ['.js', '.ts', '.tsx', '.jsx', '.py', '.go', '.rs', '.java', '.kt', '.cs', '.cpp', '.c', '.h', '.hpp', '.php', '.rb'];
  return exts.some((e) => s.endsWith(e));
}
function aiSignature(txt = '') {
  return /(chatgpt|claude|copilot|generated by|as an ai|llm|openai)/i.test(txt);
}
function findSecretHits(txt = '') {
  const rules = [
    { name: 'private-key', re: /-----BEGIN (RSA|EC|OPENSSH|DSA) PRIVATE KEY-----/g },
    { name: 'aws-access-key', re: /AKIA[0-9A-Z]{16}/g },
    { name: 'generic-api-key', re: /(api[_-]?key|secret|token)\s*[:=]\s*['\"][A-Za-z0-9_\-]{16,}['\"]/gi },
    { name: 'jwt', re: /eyJ[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+/g }
  ];
  const hits = [];
  for (const r of rules) {
    const m = txt.match(r.re);
    if (m?.length) hits.push({ rule: r.name, count: Math.min(m.length, 20) });
  }
  return hits;
}
function sumFilesStats(files) {
  let additions = 0,
    deletions = 0,
    filesChanged = 0;
  for (const f of files) {
    additions += Number(f.additions || 0);
    deletions += Number(f.deletions || 0);
    filesChanged += 1;
  }
  return { additions, deletions, filesChanged, changes: additions + deletions };
}
function computeScore({ stats, testChangeRatio, hasDepFiles, invalidDepsCount, secretHitsCount, hasAiSig, hasDocsChange, hasCodeChange }) {
  let score = 0;
  if (stats.filesChanged > 25) score += 18;
  else if (stats.filesChanged > 12) score += 10;

  if (stats.changes > 2000) score += 22;
  else if (stats.changes > 1000) score += 15;
  else if (stats.changes > 400) score += 8;

  if (hasCodeChange && !hasDocsChange) score += 6;

  if (hasCodeChange && testChangeRatio < 0.05) score += 16;
  else if (hasCodeChange && testChangeRatio < 0.12) score += 8;

  if (hasDepFiles && invalidDepsCount > 0) score += 28;

  if (secretHitsCount > 0) score += 35;

  if (hasAiSig) score += 8;

  return Math.max(0, Math.min(100, score));
}
function riskLabel(score) {
  if (score >= 65) return 'HIGH';
  if (score >= 35) return 'MEDIUM';
  return 'LOW';
}

async function main() {
  const usage = `Usage:\n  node cli.js owner/repo <prNumber> [--token=...]\n`;
  const repo = argv[2];
  const pr = argv[3];
  const tokenArg = argv.find((a) => a.startsWith('--token='));
  const token = tokenArg ? tokenArg.split('=')[1] : process.env.GITHUB_TOKEN || '';

  if (!repo || !pr) {
    console.error(usage);
    exit(1);
  }

  const [owner, name] = repo.split('/');
  const prNum = Number(pr);
  const prData = await gh(`https://api.github.com/repos/${owner}/${name}/pulls/${prNum}`, token);
  const commits = await gh(`https://api.github.com/repos/${owner}/${name}/pulls/${prNum}/commits?per_page=100`, token);

  let files = [];
  for (let page = 1; page <= 10; page++) {
    const chunk = await gh(`https://api.github.com/repos/${owner}/${name}/pulls/${prNum}/files?per_page=100&page=${page}`, token);
    files = files.concat(chunk);
    if (!chunk.length || chunk.length < 100) break;
  }

  const stats = sumFilesStats(files);
  const hasCodeChange = files.some((f) => pathLooksLikeCode(f.filename));
  const hasDocsChange = files.some((f) => pathLooksLikeDocs(f.filename));
  const testFiles = files.filter((f) => pathLooksLikeTest(f.filename));
  const testChanges = testFiles.reduce((a, f) => a + Number(f.additions || 0) + Number(f.deletions || 0), 0);
  const testChangeRatio = stats.changes ? testChanges / stats.changes : 0;

  const patchesBlob = files.map((f) => `FILE:${f.filename}\n${f.patch || ''}`).join('\n\n');
  const secretHits = findSecretHits(patchesBlob);
  const hasAiSig = aiSignature((prData.body || '') + '\n' + commits.map((c) => c.commit?.message || '').join('\n'));

  const depFiles = files.filter((f) => ['package.json', 'requirements.txt', 'pyproject.toml'].includes(f.filename.split('/').pop()));
  const hasDepFiles = depFiles.length > 0;

  const score = computeScore({
    stats,
    testChangeRatio,
    hasDepFiles,
    invalidDepsCount: 0,
    secretHitsCount: secretHits.reduce((a, x) => a + x.count, 0),
    hasAiSig,
    hasDocsChange,
    hasCodeChange
  });

  console.log('# SlopSieve report');
  console.log(`- Repo: ${repo}`);
  console.log(`- PR: #${prNum} — ${prData.title}`);
  console.log(`- URL: ${prData.html_url}`);
  console.log(`- Risk: ${riskLabel(score)} (${score}/100)`);
  console.log(`- Files: ${stats.filesChanged}, Lines changed: ${stats.changes} (+${stats.additions}/-${stats.deletions})`);
  console.log(`- Tests ratio: ${(testChangeRatio * 100).toFixed(1)}%`);
  console.log(`- AI signature: ${hasAiSig ? 'yes' : 'no'}`);
  if (secretHits.length) {
    console.log('\n## Potential secrets');
    console.log('```json');
    console.log(JSON.stringify(secretHits, null, 2));
    console.log('```');
  }
}

main().catch((e) => {
  console.error(e.message || e);
  process.exit(1);
});
