function authHeaders(token) {
  const h = {
    accept: 'application/vnd.github+json',
    'user-agent': 'slopsieve/0.1'
  };
  if (token && token.trim()) h.authorization = `Bearer ${token.trim()}`;
  return h;
}

async function ghFetch(url, token) {
  const resp = await fetch(url, { headers: authHeaders(token) });
  const text = await resp.text();
  if (!resp.ok) {
    throw new Error(`GitHub ${resp.status} for ${url}: ${text.slice(0, 200)}`);
  }
  return text ? JSON.parse(text) : null;
}

function sumFilesStats(files) {
  let additions = 0, deletions = 0, filesChanged = 0;
  for (const f of files) {
    additions += Number(f.additions || 0);
    deletions += Number(f.deletions || 0);
    filesChanged += 1;
  }
  return { additions, deletions, filesChanged, changes: additions + deletions };
}

function pathLooksLikeTest(p = '') {
  const s = p.toLowerCase();
  return s.includes('/test/') || s.includes('/tests/') || s.includes('__tests__') || s.endsWith('.spec.js') || s.endsWith('.test.js') || s.endsWith('.spec.ts') || s.endsWith('.test.ts') || s.includes('pytest') || s.includes('spec/');
}

function pathLooksLikeDocs(p = '') {
  const s = p.toLowerCase();
  return s.startsWith('docs/') || s.includes('/docs/') || s.endsWith('.md') || s.endsWith('.mdx') || s.includes('readme');
}

function pathLooksLikeCode(p = '') {
  const s = p.toLowerCase();
  const exts = ['.js','.ts','.tsx','.jsx','.py','.go','.rs','.java','.kt','.cs','.cpp','.c','.h','.hpp','.php','.rb'];
  return exts.some(e => s.endsWith(e));
}

function findSecretHits(textBlob = '') {
  const hits = [];
  const rules = [
    { name: 'private-key', re: /-----BEGIN (RSA|EC|OPENSSH|DSA) PRIVATE KEY-----/g },
    { name: 'aws-access-key', re: /AKIA[0-9A-Z]{16}/g },
    { name: 'generic-api-key', re: /(api[_-]?key|secret|token)\s*[:=]\s*['\"][A-Za-z0-9_\-]{16,}['\"]/gi },
    { name: 'jwt', re: /eyJ[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+/g }
  ];
  for (const r of rules) {
    const m = textBlob.match(r.re);
    if (m && m.length) hits.push({ rule: r.name, count: Math.min(m.length, 20) });
  }
  return hits;
}

function aiSignature(textBlob = '') {
  const re = /(chatgpt|claude|copilot|generated by|as an ai|llm|openai)/i;
  return re.test(textBlob);
}

async function validateNpmPackages(pkgNames = []) {
  const out = [];
  const unique = [...new Set(pkgNames)].slice(0, 30);
  for (const name of unique) {
    try {
      const resp = await fetch(`https://registry.npmjs.org/${encodeURIComponent(name)}`, { headers: { 'user-agent': 'slopsieve/0.1' } });
      out.push({ name, ok: resp.ok, status: resp.status });
    } catch (e) {
      out.push({ name, ok: false, status: 0, error: String(e.message || e) });
    }
  }
  return out;
}

async function validatePyPiPackages(pkgNames = []) {
  const out = [];
  const unique = [...new Set(pkgNames)].slice(0, 30);
  for (const name of unique) {
    const safe = name.replace(/[^A-Za-z0-9_.-]/g, '');
    if (!safe) continue;
    try {
      const resp = await fetch(`https://pypi.org/pypi/${encodeURIComponent(safe)}/json`, { headers: { 'user-agent': 'slopsieve/0.1' } });
      out.push({ name: safe, ok: resp.ok, status: resp.status });
    } catch (e) {
      out.push({ name: safe, ok: false, status: 0, error: String(e.message || e) });
    }
  }
  return out;
}

function parseRequirements(txt = '') {
  return txt
    .split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.startsWith('#') && !l.startsWith('-'))
    .map(l => l.split(/[<>=!~\[]/)[0].trim())
    .filter(Boolean)
    .slice(0, 200);
}

function computeScore({ stats, testChangeRatio, hasDepFiles, invalidDepsCount, secretHitsCount, hasAiSig, hasDocsChange, hasCodeChange }) {
  let score = 0;
  if (stats.filesChanged > 25) score += 18;
  else if (stats.filesChanged > 12) score += 10;

  if (stats.changes > 2000) score += 22;
  else if (stats.changes > 1000) score += 15;
  else if (stats.changes > 400) score += 8;

  if (hasCodeChange && !hasDocsChange) score += 6;

  if (hasCodeChange && testChangeRatio < 0.05) score += 16;
  else if (hasCodeChange && testChangeRatio < 0.12) score += 8;

  if (hasDepFiles && invalidDepsCount > 0) score += 28;

  if (secretHitsCount > 0) score += 35;

  if (hasAiSig) score += 8;

  return Math.max(0, Math.min(100, score));
}

function riskLabel(score) {
  if (score >= 65) return { label: 'HIGH', cls: 'bad' };
  if (score >= 35) return { label: 'MEDIUM', cls: 'warn' };
  return { label: 'LOW', cls: 'ok' };
}

function mdChecklist(findings) {
  const lines = [];
  lines.push(`# SlopSieve checklist`);
  lines.push('');
  lines.push(`**Risk:** ${findings.risk.label} (${findings.score}/100)`);
  lines.push('');
  lines.push('## Quick checks');
  lines.push('- [ ] Pull branch locally + run full test suite');
  lines.push('- [ ] Run linter/formatter + ensure CI is green');
  if (findings.secretHits?.length) {
    lines.push('- [ ] **BLOCKER:** Potential secret(s) detected — remove, rotate, and invalidate exposed credentials');
  }
  if (findings.invalidDeps?.length) {
    lines.push('- [ ] **BLOCKER:** Validate new/changed dependencies exist and are legitimate');
  }
  if (findings.hasAiSig) {
    lines.push('- [ ] Treat as AI-assisted: scrutinize error handling, edge cases, and overconfident logic');
  }
  if (findings.testChangeRatio < 0.05 && findings.hasCodeChange) {
    lines.push('- [ ] Ask for tests: changes are mostly code with little/no test coverage');
  }
  lines.push('- [ ] Confirm docs/README updates if behavior changed');
  lines.push('- [ ] Spot-check security: input validation, authz, injection, path traversal');
  lines.push('');
  lines.push('## Context');
  lines.push(`- Repo: ${findings.repo}`);
  lines.push(`- PR: #${findings.pr} — ${findings.prTitle}`);
  lines.push(`- Files changed: ${findings.stats.filesChanged}, Lines changed: ${findings.stats.changes} (+${findings.stats.additions}/-${findings.stats.deletions})`);
  return lines.join('\n');
}

async function analyzePR({ repo, pr, token }) {
  const [owner, name] = repo.split('/');
  if (!owner || !name) throw new Error('Repo must look like owner/name');
  const prNum = Number(pr);
  if (!Number.isFinite(prNum) || prNum <= 0) throw new Error('PR must be a positive number');

  const prData = await ghFetch(`https://api.github.com/repos/${owner}/${name}/pulls/${prNum}`, token);
  const commits = await ghFetch(`https://api.github.com/repos/${owner}/${name}/pulls/${prNum}/commits?per_page=100`, token);

  // Pull files (paginate)
  let files = [];
  for (let page = 1; page <= 10; page++) {
    const chunk = await ghFetch(`https://api.github.com/repos/${owner}/${name}/pulls/${prNum}/files?per_page=100&page=${page}`, token);
    files = files.concat(chunk);
    if (!chunk.length || chunk.length < 100) break;
  }

  const stats = sumFilesStats(files);
  const hasCodeChange = files.some(f => pathLooksLikeCode(f.filename));
  const hasDocsChange = files.some(f => pathLooksLikeDocs(f.filename));
  const testFiles = files.filter(f => pathLooksLikeTest(f.filename));
  const testChanges = testFiles.reduce((a, f) => a + Number(f.additions || 0) + Number(f.deletions || 0), 0);
  const testChangeRatio = stats.changes ? (testChanges / stats.changes) : 0;

  const patchesBlob = files.map(f => `FILE:${f.filename}\n${f.patch || ''}`).join('\n\n');
  const secretHits = findSecretHits(patchesBlob);
  const hasAiSig = aiSignature((prData.body || '') + '\n' + commits.map(c => c.commit?.message || '').join('\n'));

  // dependency hallucination checks (only when dep files changed)
  const depFiles = files.filter(f => ['package.json', 'requirements.txt', 'pyproject.toml'].includes(f.filename.split('/').pop()));
  const hasDepFiles = depFiles.length > 0;

  let invalidDeps = [];
  const depEvidence = [];

  for (const f of depFiles) {
    const base = f.filename.split('/').pop();
    if (base === 'package.json' && f.raw_url) {
      const raw = await fetch(f.raw_url, { headers: { 'user-agent': 'slopsieve/0.1' } }).then(r => r.text());
      try {
        const parsed = JSON.parse(raw);
        const deps = Object.keys({ ...(parsed.dependencies || {}), ...(parsed.devDependencies || {}) }).slice(0, 200);
        const checks = await validateNpmPackages(deps);
        const bad = checks.filter(x => !x.ok);
        invalidDeps.push(...bad.map(b => ({ ecosystem: 'npm', name: b.name, status: b.status })));
        depEvidence.push({ file: f.filename, ecosystem: 'npm', checked: checks.length, invalid: bad.length });
      } catch {
        depEvidence.push({ file: f.filename, ecosystem: 'npm', error: 'Failed to parse package.json' });
      }
    }

    if (base === 'requirements.txt' && f.raw_url) {
      const raw = await fetch(f.raw_url, { headers: { 'user-agent': 'slopsieve/0.1' } }).then(r => r.text());
      const pkgs = parseRequirements(raw);
      const checks = await validatePyPiPackages(pkgs);
      const bad = checks.filter(x => !x.ok);
      invalidDeps.push(...bad.map(b => ({ ecosystem: 'pypi', name: b.name, status: b.status })));
      depEvidence.push({ file: f.filename, ecosystem: 'pypi', checked: checks.length, invalid: bad.length });
    }
  }

  const score = computeScore({
    stats,
    testChangeRatio,
    hasDepFiles,
    invalidDepsCount: invalidDeps.length,
    secretHitsCount: secretHits.reduce((a, x) => a + x.count, 0),
    hasAiSig,
    hasDocsChange,
    hasCodeChange
  });

  const risk = riskLabel(score);

  const findings = {
    repo,
    pr: prNum,
    prTitle: prData.title,
    prUrl: prData.html_url,
    author: prData.user?.login,
    createdAt: prData.created_at,
    updatedAt: prData.updated_at,
    stats,
    testChangeRatio,
    hasAiSig,
    secretHits,
    invalidDeps,
    depEvidence,
    score,
    risk,
    hasDocsChange,
    hasCodeChange
  };

  return {
    findings,
    markdown: mdChecklist(findings)
  };
}

export {
  authHeaders,
  ghFetch,
  sumFilesStats,
  pathLooksLikeTest,
  pathLooksLikeDocs,
  pathLooksLikeCode,
  findSecretHits,
  aiSignature,
  validateNpmPackages,
  validatePyPiPackages,
  parseRequirements,
  computeScore,
  riskLabel,
  mdChecklist,
  analyzePR
};
